# Generated by Django 4.0.10 on 2023-03-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, default='', max_length=3000, verbose_name='Ссылка на источник'),
        ),
    ]
